### ISSUE TITLE
Passing data between controllers and avoiding double rendering

### ISSUE THREAD

**Issue by vmihailenco** [angular/router#144]
Hi,

Assume I have following routes:

```
/projects/:projectId, {projects: "projectList"}
/projects/:projectId/articles/:articleId, {article: "articleDetail"}
```

What is the recommended way to:
- access `project` set in the `ProjectListController`
- wait for the `ProjectListController` to be activated before activating `ArticleDetailController`, so `ProjectListController.project` is available. Otherwise `ArticleDetailController` is rendered twice: first time with `undefined` project and second time when project is set by the `ProjectListController`.

Thanks.

**Comment by jvandemo** [comment]
I think the recommended way would be to:

`ProjectListController `:
```javascript
module.controller('ProjectListController', function(){

  // fetch the project in the 'activate' lifecycle hook
  // e.g. using $http and return promise
  this.activate = function(){
    ...
  };
});
```

`components/project-list/project-list.html`:
```xml
<h1>Project {{ projectList.project.title }}</h1>
<div ng-viewport="article"></div>
```

`ArticleDetailController `:
```javascript
module.controller('ArticleDetailController', function(){

  // fetch the article in the 'activate' lifecycle hook
  // e.g. using $http and return promise
  this.activate = function(){
    ...
  };
});
```

`components/article/article.html`:
```xml
<h2>Article {{ articleDetail.article.title }}</h2>
```

**Comment by vmihailenco** [comment]
Thanks for the response.

That was my original thought too, but it is very inconvenient that I have to split my templates in order to use new router. E.g. instead of 1 template like:

```
<html>
  <header>
    <div ng-viewport="projects"></div>
  </header>
  <sidebar>
    <div ng-viewport="categories"></div>
  </sidebar>
  <content>
    <div ng-viewport="article"></div>
  </content>
</html>
```

I have to define 4 nested templates in order to support URL like `projects/1/categories/2/articles/3`:
- index.html defines `projects` view port
- projects-list.html defines `categories` view port
- categories-list.html defines `article` view port
- article.html

Do I misunderstand anything?

**Comment by jvandemo** [comment]
Not necessarily. It depends on the structure of your application.

If you always have a url like `projects/1/categories/2/articles/3`, then you can create a single component.

Assume the following route:

```javascript
$router.config([{
  path: '/projects/:pid/categories/:cid/articles/:aid',
  component: 'projectList'
}]);
```

`ProjectListController`:
```javascript
module.controller('ProjectListController', function(){

  var ctrl = this;

  // fetch the project, category and article in the 'activate' lifecycle hook
  // e.g. using $http and return promise that is resolved when all
  // resources have been loaded e.g. using $q.all()
  this.activate = function(){

    // Get project and assign to controller
    // property in then() success handler
    var promise1 = $http.get(...).then(function(response){
      ctrl.project = response; // Parse response if needed
    });

    // Get category and assign to controller
    // property in then() success handler
    var promise2 = $http.get(...).then(function(response){
      ctrl.category = response; // Parse response if needed
    });

    // Get article and assign to controller
    // property in then() success handler
    var promise3 = $http.get(...).then(function(response){
      ctrl.article = response; // Parse response if needed
    });

    // Tell router to wait until everything has been resolved
    return $q.all([promise1, promise2, promise3]);
  };
});
```

`components/project-list/project-list.html`:

```xml
<html>
  <header>
    <div project="projectList.project"></div>
  </header>
  <sidebar>
   <div category="projectList.category"></div>
  </sidebar>
  <content>
    <div article="projectList.article"></div>
  </content>
</html>
```

However, if you need the handle the paths:

- `projects/`
- `projects/1/`
- `projects/1/categories/`
- `projects/1/categories/2/`
- `projects/1/categories/2/articles/`
- `projects/1/categories/2/articles/3`

differently, then you are probably better of using multiple components to keep things more granular and self-contained.

Does that make sense?

**Comment by vmihailenco** [comment]
That makes sense, but it does not address my concerns about splitting templates when I have paths like:
- projects/
- projects/1/
- projects/1/categories/

etc. And honestly I can't say that my requirements are very specific or rare.

**Comment by jvandemo** [comment]
Not sure if I correctly understand your concern.

In a router like `ui-router`, you would use different templates for

- `projects/`
- `projects/1/`
- `projects/1/categories/`

too if you want them to render differently, or am I misunderstanding your point?

Can you maybe give a more detailed example of what your views look like so we can get a better understanding?

Thanks in advance!

**Comment by vmihailenco** [comment]
Layout in https://github.com/angular/router/issues/144#issuecomment-78847743 is a good example of my router.

>too if you want them to render differently

Yes, but with ui-router I inject different templates into view ports. I don't have to split my layout into nested parts. E.g. with ui-router it looks like this:

```
  $stateProvider.state
    name: 'projects'
    url: '/projects'
    views:
      'projects':
        controller: 'ProjectsController as projects'
      'categories':
        templateUrl: 'no-categories.html'
      'article':
        templateUrl: 'no-article.html'

  $stateProvider.state
    name: 'project'
    parent: 'projects'
    url: '/:project-id'
    views:
      'categories':
        controller: 'CategoriesController as categories'

  $stateProvider.state
    name: 'article'
    parent: 'project'
    url: '/categories/:categoryId/articles/:articleId'
    views:
      'article':
        controller: 'ArticleController as article'
```
